title:		"Artikel PPL"
author:     "KentaBisma"
urlweb:     "https://kentabisma.github.io/artikel-ppl"
urlgithub:      "https://github.com/kentabisma/artikel-ppl"
urlghpage:      "https://kentabisma.github.io/artikel-ppl"
mygithub:       "https://github.com/kentabisma"
keywords:       "jekyll, testing"
sitemap:        "true"
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
